version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Alperkaan11
    ports:
      - "1433:1433"
    networks:
      - sql-network
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:

networks:
  sql-network:
    driver: bridge
